spring:
  datasource:
    url: jdbc:mysql://database-1.cfa1lcbppqdm.eu-central-1.rds.amazonaws.com:3306/images?useSSL=false
    username: admin
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      INDENT_OUTPUT: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop #disable spring hibernate schema creation
  sql:
    init:
      mode: always #initialize all type of database, not only h2 which is default one
      continue-on-error: true

server:
  port: 8081

aws:
  accessKey: AKIA2RHQG7XODNHYSI7Z
  secretKey: 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
  s3BucketName: uploaded-images-storage

