spring:
  datasource:
    url: jdbc:mysql://{DB_HOST}:3306/images?useSSL=false
    username: admin
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      INDENT_OUTPUT: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create #disable spring hibernate schema creation
  sql:
    init:
      mode: always #initialize all type of database, not only h2 which is default one
      continue-on-error: true

server:
  port: 8081

aws:
  accessKey: 
  secretKey: 
  s3BucketName: 
  snsTopicArn: 
  sqsQueueUrl: 
  lambda-function-name: 
