version: 0.2

phases:
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew clean build
  post_build:
    commands:
      - aws cloudformation package --template-file template.yaml --output-template-file package.yaml --s3-bucket code-build-artifacts-s3
artifacts:
  files:
    - package.yaml